# Generated by Django 5.0.4 on 2024-05-10 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_catagroy_alter_product_options_product_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCatagroy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='SubCatagroy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='catphoto')),
                ('main_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.maincatagroy')),
            ],
        ),
        migrations.DeleteModel(
            name='Catagroy',
        ),
    ]
