# Generated by Django 5.0.4 on 2024-05-12 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_maincatagroy_subcatagroy_delete_catagroy'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subcatagroy'),
        ),
    ]
