# Generated by Django 5.0.4 on 2024-05-23 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_orderitem_status_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 9, 23, 30, 561118, tzinfo=datetime.timezone.utc)),
        ),
    ]
